### PR TITLE
add more options, introduce opinionated change

### PR DESCRIPTION
**Pull request by nopeless**

### CODE REVIEW

**Comment by nopeless** [comment]
Just wanted to add multiline support for strings

ended up
 - adding multiline support (while preserving indent)
 - adding array support
 - fixed circular reference crash
 - add collapsable array and objects (not tested yet)

These change are all compatible with old behavior except
 - (obviously) multiline outputs are now indented
 - setting `breakCircularWith` to `null` `console.warn`s deprecation warning
 - arrays are rendered
 - overriding the `renderFn` does not render objects and arrays no matter what (only renders one of collapsed, circular ref, or "")

I'm open to feedback so let me know what you think

**Comment by nopeless** [comment]
Oh and, `renderFn` uses the same formatter that `console.log` uses which is the `util.format` function. This won't affect many people but I'm assuming that many will expect a formatting that follows `console.log` instead of `Object.toString`

**Comment by simlu** [comment]
Awesome! I don't have time to do a full review right now, but will try to look at it later tonight.

**Comment by nopeless** [comment]
take your time

**Comment by nopeless** [comment]
Above commit "fixes" the issue of empty object entries not being rendered

**Comment by nopeless** [comment]
bump

**Comment by nopeless** [comment]
bump

**Comment by nopeless** [comment]
@simlu , I am housekeeping my PRs. Id like you to review this

**Comment by nopeless** [comment]
Closing this as no interest was given, I'm sorry to see this happen

**Comment by simlu** [comment]
Hello nopeless! I'm sorry I didn't give more feedback on this.

The biggest problem with this PR is that it does lots of different things.

I think the changes themselves are good, but it is much easier for me to review small changesets.

If you are willing to open small prs, maybe one at a time, I think there is a very good chance we can get these changes into the library!

Cheers, L~

**Pull request closed without merging**
